services: 
  db:
    image: mysql:9.1.0
    container_name: mysql-rt 
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=UTC
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_volume:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file: 
      - path: .env.development
        required: true
  s3:
    image: minio/minio
    container_name: minio-rt
    restart: always
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}" # Console Port
    volumes:
      - minio_volume:/data
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}" 
    env_file:
      - path: .env
        required: false # default 
      - path: .env.development
        required: false
  redis:
    image: redis:7.4.2-alpine
    container_name: redis-rt
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_volume:/data
    env_file:
      - path: .env
        required: false # default 
      - path: .env.development
        required: false

volumes:
  mysql_volume:
  minio_volume:
  redis_volume:
