{
 "title": "MySQL Innodb Cluster",
 "description": "A dashboard for Innodb Cluster monitoring",
 "tags": [
  "HA",
  "MySQL",
  "Innodb"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(mysql_performance_schema_group_replication_replication_group_members_STATUS, INSTANCE_NAME)"
   }
  ]
 },
 "panels": [
  { "title": "GENERAL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "type": "text", "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 }, "content": "##### MySQL Instances" },
  {
   "title": "MySQL State",
   "type": "btplc-status-dot-panel",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 3 },
   "format": "none",
   "targets": [
    {
     "expr": "mysql_up{instance=~\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ETAT DU CLUSTER",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "mysql_performance_schema_group_replication_replication_group_members_STATUS{instance=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "MySQL ROUTER",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "mysql_performance_schema_group_replication_replication_router_VALUE{instance=~\"$cluster\"}"
    }
   ]
  },
  { "title": "Node informations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "[$cluster] InnoDB Row Operations",
   "type": "graph",
   "description": "**InnoDB Row Operations**\n\nThis graph allows you to see which operations occur and the number of rows affected per operation. A graph like Queries Per Second will give you an idea of queries, but one query could effect millions of rows.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "repeat": "cluster",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_innodb_row_ops_total{instance=~\"$cluster\"}[$interval]) or irate(mysql_global_status_innodb_row_ops_total{instance=~\"$cluster\"}[5m])",
     "legendFormat": "Rows {{ operation }}"
    }
   ]
  },
  {
   "title": "[$cluster] Network usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "repeat": "cluster",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes{instance=~\"$cluster\", device!=\"lo\"}[1h]))",
     "legendFormat": "Inbound"
    },
    {
     "expr": "sum(increase(node_network_transmit_bytes{instance=~\"$cluster\", device!=\"lo\"}[1h]))",
     "legendFormat": "Outbound"
    }
   ]
  }
 ]
}