bind 0.0.0.0
sentinel monitor mymaster 172.50.0.2 6379 2
sentinel down-after-milliseconds mymaster 10000
sentinel failover-timeout mymaster 18000
sentinel parallel-syncs mymaster 1
sentinel resolve-hostnames yes

